KingTexasListener = {
    Instance = nil,
    MainC = nil,
    ControllerMgr = nil,
    ViewMgr = nil,
    EventSys = nil,
    LuaHelper = nil,
    TbDataMgr = nil,
    TbDataMgrBase = nil,
}

function KingTexasListener:new(o)
    o = o or {}
    setmetatable(o, self)
    self.__index = self
    if (self.Instance == nil)
    then
        self.Instance = o
    end
    return self.Instance
end

function KingTexasListener:onCreate()
    print("KingTexasListener:onCreate")
    self.ResourcesRowPathRoot = "Resources.KingTexasRaw/"

    local uni_g = CS.UnityEngine.GameObject("UniWebView")
    self.UniWebView = CS.Casinos.LuaHelper.AddUniWebViewToObj(uni_g)
    self.UniWebView.Frame = CS.UnityEngine.Rect(0, 0, CS.UnityEngine.Screen.width, CS.UnityEngine.Screen.height)
    self:_regLuaFilePath()

    self.MainC = MainC:new(nil)
    self.Lanch = ControllerLaunch:new(nil)
    self.CreateLogin = false
    self.LoadTbDataDone = false
    --CS.Casinos.CasinosContext.Instance.CasinosLua:doString("LuaHelper")
    --self.LuaHelper = LuaHelper:new(nil)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TexasHelper")

    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataMgr")
    self.TbDataMgr = TbDataMgr:new(nil)
    self.TbDataMgr:onCreate()
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataBase")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataMgrBase")
    self:RegTbData()

    local t_db = {}
    local list_db = CS.Casinos.CasinosContext.Instance.UserConfig:getDBName()
    for i = 0, list_db.Count - 1 do
        t_db[i] = CS.Casinos.CasinosContext.Instance.PathMgr:combinePersistentDataPath("Resources.KingTexasRaw/Config/" .. list_db[i] .. ".db")
    end
    self.TbDataMgrBase = TbDataMgrBase:new(nil, self.TbDataMgr, t_db,
            function()
                self:LoadDataDone()
            end
    )

    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("EventSys")
    self.EventSys = EventSys:new(nil)
    self.EventSys:onCreate()

    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewMgr")
    self.ViewMgr = ViewMgr:new(nil)
    self.ViewMgr:onCreate("Resources.KingTexas/Ui/", "Resources.KingTexasRaw/")
    self.ViewMgr.TbDataMgr = self.TbDataMgr
    self:_regView()
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewHelper")
    ViewHelper:new(nil)

    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("LanBase")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("LanEn")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("LanMgr")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("LanZh")

    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("UiChipShowHelper")
    self.UiChipShowHelper = UiChipShowHelper:new(nil)
    --CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ParticleHelper")

    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("MessagePack")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("json")
    self.Json = require("json")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("RPC")
    local rpc = RPC:new(nil)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("SessionMgr")
    SessionMgr:new(nil)

    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ControllerMgr")
    self.ControllerMgr = ControllerMgr:new(nil)
    self.ControllerMgr:OnCreate()
    self.ControllerMgr.TbDataMgr = self.TbDataMgr
    self.ControllerMgr.RPC = rpc
    self.ControllerMgr.Listener = self
    self:_regController()
    self.ViewMgr.ControllerMgr = self.ControllerMgr
    self.ViewMgr.RPC = rpc
    self.ViewMgr.Listener = self

    self:_addUiPackage()


end

function KingTexasListener:onDestroy()
    if (self.ViewMgr ~= nil)
    then
        self.ViewMgr:onDestroy()
    end

    if (self.ControllerMgr ~= nil)
    then
        self.ControllerMgr:OnDestroy()
    end
end

function KingTexasListener:onUpdate(tm)
    if (self.ViewMgr ~= nil)
    then
        self.ViewMgr:onUpdate(tm)
    end

    if (self.ControllerMgr ~= nil)
    then
        self.ControllerMgr:OnUpdate(tm)
    end

    if (self.TbDataMgr ~= nil)
    then
        self.TbDataMgr:onUpdate(tm)
    end

    if (self.LoadTbDataDone == true and self.Lanch.InitializeDone == true and self.CreateLogin == false)
    then
        self.CreateLogin = true
        self.ControllerMgr:CreateController("UCenter", nil, nil)
        self.ControllerMgr:CreateController("Login", nil, nil)
    end

    if self.PicCapture ~= nil then
        self.PicCapture:OnUpdate()
    end

    if (CS.UnityEngine.Input.GetKeyDown(CS.UnityEngine.KeyCode.Escape))
    then
        local ui_quit = self.ViewMgr:getView("QuitOrBack")
        if (ui_quit == nil)
        then
            ui_quit = self.ViewMgr:createView("QuitOrBack")
            if ui_quit ~= nil then
                ui_quit:setQuitTimeAndIfCanBackGameAndTips(10, true, "")
            end
        end
    end
end

function KingTexasListener.OnApplicationPause(is_pause)
    print("OnApplicationPause   "..tostring(is_pause))
    if (is_pause == false)
    then
        local lis = KingTexasListener:new(nil)
        local ev = lis.ViewMgr:getEv("EvEntityGetDesktopData")
        if (ev == nil)
        then
            ev = EvEntityGetDesktopData:new(nil)
        end
        lis.ViewMgr:sendEv(ev)

        local ev1 = lis.ViewMgr:getEv("EvEntityRequestGetDesktopHData")
        if (ev1 == nil)
        then
            ev1 = EvEntityRequestGetDesktopHData:new(nil)
        end
        lis.ViewMgr:sendEv(ev1)
    end
end

function KingTexasListener:CreateController(table_data)

end

function KingTexasListener:_regLuaFilePath()
    local casinos_context = CS.Casinos.CasinosContext.Instance
    casinos_context:regLuaFilePath("MessagePack/", "MessagePack")
    casinos_context:regLuaFilePath("Json/", "json")
    casinos_context:regLuaFilePath("Lan/", "LanBase", "LanEn", "LanMgr", "LanZh")
    casinos_context:regLuaFilePath("Controller/", "ControllerMgr", "ControllerBase", "ControllerFactory",
            "ControllerActivity", "ControllerActor", "ControllerBag", "ControllerDesk", "ControllerDeskH", "ControllerGrow",
            "ControllerIM", "ControllerLobby", "ControllerLotteryTicket", "ControllerMarquee", "ControllerPlayer",
            "ControllerRanking", "ControllerTrade", "ControllerLogin", "ControllerUCenter", "Prop", "OnLineReward", "ControllerMTT")
    casinos_context:regLuaFilePath("Item/", "Item", "ItemData1", "Unit", "UnitBilling", "UnitConsume", "UnitGiftNormal", "UnitGiftTmp", "UnitMagicExpression",
									"UnitGoodsVoucher","UnitGoldPackage","ItemActivity")
    casinos_context:regLuaFilePath("IM/", "IMChat", "IMChatRecord", "IMFriendList", "IMMailBox")
    casinos_context:regLuaFilePath("Desktop/", "DesktopPlayerTexas", "DesktopBase", "DesktopTexas", "DesktopHelperBase", "DesktopHelperTexas",
            "DesktopTypeBase", "DesktopTexasClassic", "DesktopTexasMTT")
    casinos_context:regLuaFilePath("DesktopH/", "DesktopHBase", "DesktopHTexas")
    casinos_context:regLuaFilePath("Model/", "ModelBase", "ModelReaderBase", "ModelCommon", "ModelAccount", "ModelUCenter", "ModelTrade", "ModelDesktop",
            "ModelDesktopTexas", "ModelDesktopTexasMatch","ModelActor","ModelActivity","ModelGrow","ModelPlayer","ModelRank","ModelMarquee","ModelWallet")
    casinos_context:regLuaFilePath("View/", "ViewMgr", "ViewFactory", "ViewBase", "ViewLoading", "ViewMsgBox", "ViewSecurityCode", "ViewDesktopChatParent"
    , "ViewFloatMsg", "ViewHeadIcon", "ViewHeadIconBig", "ViewMailDetail", "ViewNotice", "ViewPayType", "ViewVIPSign", "ViewWaitingCountDown"
    , "ViewPermanentPosMsg", "ViewPool", "ViewShootingText", "ViewTakePhoto", "ViewWaiting", "ViewWaitingCountDown", "ViewOnlineReward",
            "UiMainPlayerInfo", "ViewActivityPopUpBox","ViewShare")
    casinos_context:regLuaFilePath("View/Desktop/", "DealerEx", "UiCardCommonEx", "UiCardDealingEx", "UiChipEx", "UiChipMgrEx", "ViewPlayerGiftAndVIP"
    , "ViewDesktopTypeBase", "ViewMTTGameResult", "ViewMTTProcess")
    casinos_context:regLuaFilePath("View/Desktop/Texas/", "PlayerSeatWidgetControllerTexas","PlayerShowTips","PlayerOperateAni", "ViewDesktopHintsTexas", "ViewDesktopMenuTexas", "ViewDesktopPlayerInfoTexas",
            "ViewDesktopPlayerOperateTexas", "DesktopFastBet","ViewDesktopTexas", "ViewHandCardTexas", "ViewLockChatTexas", "ViewPotTexasPoker", "ViewTexasClassic", "ViewTexasMTT")
    casinos_context:regLuaFilePath("View/DesktopH/", "DesktopHBankPlayer", "DesktopHBetPot", "DesktopHCard", "DesktopHCards", "DesktopHCardTypeBase", "DesktopHCardTypeTexas"
    , "DesktopHChair", "DesktopHDealer", "DesktopHGoldPool", "DesktopHRewardPot", "DesktopHSelf", "DesktopHStandPlayer"
    , "DesktopHUiGold", "ViewDesktopH", "ViewDesktopHBankList", "ViewDesktopHBase", "ViewDesktopHBetReward", "ViewDesktopHCardType", "ViewDesktopHHelp"
    , "ViewDesktopHHistory", "ViewDesktopHMenu", "ViewDesktopHResult", "ViewDesktopHSetCardType", "ViewDesktopHTexas")
    casinos_context:regLuaFilePath("View/DesktopH/Item/", "ItemDesktopHBeBankPlayerInfo", "ItemDesktopHBetOperate", "ItemDesktopHBetPot", "ItemDesktopHBetReward", "ItemDesktopHGameEndPotResult"
    , "ItemDesktopHGameEndWinPlayer", "ItemDesktopHHistroy", "ItemDesktopHSeat", "ItemDesktopHSetCardType", "ItemUiDesktopHTongPei", "ItemUiDesktopHTongSha")
    --[[casinos_context:regLuaFilePath("View/ForestParty/", "ForestPartyBanker","ForestPartyCommon","ViewForestParty","ViewForestPartyBet","ViewForestPartyInfo","ViewForestPartyMenu"
                                    ,"ViewForestPartyResult","ViewForestPartyRule")
    casinos_context:regLuaFilePath("View/ForestParty/Item/", "ItemForestPartyBetOperate","ItemForestPartyLotteryResult")]]--
    casinos_context:regLuaFilePath("View/LotteryTicket/", "ViewLotteryTicket", "ViewLotteryTicketBase", "ViewLotteryTicketGFlower", "ViewLotteryTicketRewardPot", "ViewLotteryTicketTexas")
    casinos_context:regLuaFilePath("View/LotteryTicket/Item/", "ItemLotteryTicketBetOperate", "ItemLotteryTicketBetPot", "ItemLotteryTicketCard"
    , "ItemLotteryTicketHistory", "ItemLotteryTicketRewardPotPlayerInfo")
    casinos_context:regLuaFilePath("View/Item/", "ItemAttachment", "ItemMttRewardItem","ItemBetChipRange", "ItemChatEx", "ItemChatPresetMsg", "ItemDailyReward"
    , "ItemDesktopHintsInfo", "ItemDesktopRaiseOperateGFlower", "ItemHeadIcon", "ItemHeadIconWithNickName", "ItemMagicExpIcon", "ItemMagicExpSender", "ItemMail"
    , "ItemNotice", "ItemNumOperate", "ItemPlayerChatLock", "ItemPlayerReport", "ItemChatDesktop")
    casinos_context:regLuaFilePath("TbData/", "TbDataMgr", "TbDataBase", "TbDataMgrBase", "TbDataHintsInfoTexas", "TbDataActorLevel", "TbDataCommon", "TbDataDailyReward", "TbDataExpression",
            "TbDataItemType", "TbDataLanEn", "TbDataLans", "TbDataLanZh", "TbDataItem", "TbDataDesktopGFlowerBetOperate", "TbDataDesktopHBetPotGFlower",
            "TbDataLotteryTicket", "TbDataLotteryTicketBetOperate", "TbDataLotteryTicketGoldPercent", "TbDataOnlineReward", "TbDataPresetMsg", "TbDataUnitBilling",
            "TbDataUnitConsume", "TbDataUnitGiftNormal", "TbDataUnitGiftTmp", "TbDataUnitMagicExpression","TbDataUnitGoldPackage","TbDataUnitGoodsVoucher","TbDataVIPLevel", "TbDataConfigGFlowerDesktop",
            "TbDataDesktopGFlowerCreateInfo", "TbDataDesktopInfoGFlower", "TbDataConfigTexasDesktop", "TbDataDesktopInfoTexas",
            "TbDataCfigGFlowerDesktopH", "TbDataCfigGFlowerDesktopHGoldPercent", "TbDataCfigGFlowerDesktopHSysBank", "TbDataDesktopHBetOperateGFlower",
            "TbDataDesktopHInfoGFlower", "TbDataCfigNiuNiuDesktopH", "TbDataCfigNiuNiuDesktopHGoldPercent", "TbDataCfigNiuNiuDesktopHSysBank", "TbDataDesktopHBetOperateNiuNiu",
            "TbDataDesktopHBetPotNiuNiu", "TbDataDesktopHInfoNiuNiu", "TbDataCfigTexasDesktopH", "TbDataCfigTexasDesktopHGoldPercent", "TbDataCfigTexasDesktopHSysBank",
            "TbDataDesktopHBetOperateTexas", "TbDataDesktopHBetPotTexas", "TbDataDesktopHInfoTexas", "TbDataCfigZhongFBDesktopH", "TbDataCfigZhongFBDesktopHGoldPercent",
            "TbDataCfigZhongFBDesktopHSysBank", "TbDataDesktopHBetOperateZhongFB", "TbDataDesktopHBetPotZhongFB", "TbDataDesktopHInfoZhongFB", "TbDataDesktopHBetReward",
            "TbDataDesktopFastBet","TbDataTexasRaiseBlinds","TbDataTexasSnowBallRewardPlayerNum","TbDataTexasSnowBallRewardInfo")
    --"TbDataForestPartyAnimalList","TbDataForestPartyBetOperate","TbDataForestPartyBetPotMultiple","TbDataForestPartyDesktop","TbDataForestPartyLottery",
    casinos_context:regLuaFilePath("Event/", "EventSys", "EventBase", "EventView")
    casinos_context:regLuaFilePath("Helper/", "CommonLuaLoader", "ProjectDataLoader", "WWWLoader", "TexasHelper", "ViewHelper",
            "TbDataHelper", "GoldController", "UiChipShowHelper", "RPC", "CasinoHelper","Native","PicCapture")--"LuaHelper",
    casinos_context:regLuaFilePath("Resources.KingTexasRaw/Lua/View/", "ViewLogin", "ViewAbout", "ViewAgreeOrDisAddFriendRequest", "ViewBag", "ViewBank", "ViewChat"
    , "ViewChatChooseTarget", "ViewChatFriend", "ViewChipOperate", "ViewChooseLan", "ViewCreateDesktop", "ViewDailyReward"
    , "ViewDesktopChatExpression", "ViewDesktopHRewardPot", "ViewEdit", "ViewFriend", "ViewFriendOnLine", "ViewGiftDetail"
    , "ViewGiftShop", "ViewGoldTree", "ViewInviteFriendPlay", "ViewLobby", "ViewMail", "ViewMain", "ViewPlayerInfo", "ViewQuitOrBack"
    , "ViewRanking", "ViewRechargeFirst", "ViewResetPwd", "ViewShop", "ViewPlayerProfile", "ViewActivityCenter", "ViewMatchLobby"
    , "ViewApplySucceed", "ViewClub","ViewCreateMatch","ViewBlindTable","ViewClubHelp","ViewJoinMatch","ViewGetChipEffect","ViewMatchInfo","ViewEnterMatchNotify"
	, "ViewSnowBallReward","ViewEditAddress","ViewPurse")
    casinos_context:regLuaFilePath("Resources.KingTexasRaw/Lua/View/Item/", "ItemChatTargetInfo", "ItemChooseChatTargetInfo", "ItemDesktopHRewardPotPlayerInfo", "ItemGift", "ItemGiftType", "ItemInviteFriendPlay"
    , "ItemLan", "ItemLobbyDesk", "ItemLobbyDeskPlayInfo", "ItemMainOperate", "ItemRank", "ItemReportPlayerOperate", "ItemShowFriendSimple"
    , "ItemUiShopConsume", "ItemUiShopDiamond", "ItemUiShopGold", "ItemUiShopVIPInfo", "ItemVIPBuyInfo", "ItemActivityTitle","ItemUiShopGoods","ItemUiPurseGold")
    casinos_context:regLuaFilePath("Resources.KingTexasRaw/Lua/View/Item/Mtt/", "ItemMatchType", "ItemMatchInfo","ItemBlind","ItemMatchInfoBlind","ItemSnowBallRewardInfo","ItemSnowBallRewardPlayerNum"
	,"ItemMatchInfoReward","ItemMatchInfoRank")
end

function KingTexasListener:_regView()
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewLoading")
    local view_loading_fac = ViewLoadingFactory:new(nil, "Loading", "Loading", "Loading", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("Loading", view_loading_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewMsgBox")
    local view_msgbox_fac = ViewMsgBoxFactory:new(nil, "Common", "MsgBox", "Waiting", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("MsgBox", view_msgbox_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewLogin")
    local view_login_fac = ViewLoginFactory:new(nil, "Login", "Login", "Background", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("Login", view_login_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewAbout")
    local view_about_fac = ViewAboutFactory:new(nil, "About", "About", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("About", view_about_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopChatParent")
    local view_chatparent_fac = ViewDesktopChatParentFactory:new(nil, "DesktopChatParent", "DesktopChatParent", "DesktopChat", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("DesktopChatParent", view_chatparent_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewFloatMsg")
    local view_floatmsg_fac = ViewFloatMsgFactory:new(nil, "Common", "FloatMsg", "Waiting", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("FloatMsg", view_floatmsg_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewMailDetail")
    local view_maildetail_fac = ViewMailDetailFactory:new(nil, "MailDetail", "MailDetail", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("MailDetail", view_maildetail_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewNotice")
    local view_notice_fac = ViewNoticeFactory:new(nil, "Notice", "Notice", "Loading", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("Notice", view_notice_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewPayType")
    local view_paytype_fac = ViewPayTypeFactory:new(nil, "PayType", "PayType", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("PayType", view_paytype_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewPermanentPosMsg")
    local view_permanent_fac = ViewPermanentPosMsgFactory:new(nil, "Common", "PermanentPosMsg", "Loading", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("PermanentPosMsg", view_permanent_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewPool")
    local view_pool_fac = ViewPoolFactory:new(nil, "Pool", "Pool", "None", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("Pool", view_pool_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewShootingText")
    local view_shooting_fac = ViewShootingTextFactory:new(nil, "ShootingText", "ShootingText", "ShootingText", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("ShootingText", view_shooting_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewTakePhoto")
    local view_takephoto_fac = ViewTakePhotoFactory:new(nil, "TakePhoto", "TakePhoto", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("TakePhoto", view_takephoto_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewWaiting")
    local view_waiting_fac = ViewWaitingFactory:new(nil, "Common", "Waiting", "Waiting", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("Waiting", view_waiting_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewWaitingCountDown")
    local view_waiting1_fac = ViewWaitingCountDownFactory:new(nil, "Common", "WaitingCountDown", "Waiting", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("WaitingCountDown", view_waiting1_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewLotteryTicket")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewLotteryTicketBase")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewLotteryTicketRewardPot")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewLotteryTicketTexas")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemLotteryTicketBetOperate")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemLotteryTicketBetPot")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemLotteryTicketCard")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemLotteryTicketHistory")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemLotteryTicketRewardPotPlayerInfo")
    local view_lottery_fac = ViewLotteryTicketFactory:new(nil, "LotteryTicket", "LotteryTicket", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("LotteryTicket", view_lottery_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopTexas")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("PlayerSeatWidgetControllerTexas")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("PlayerOperateAni")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("PlayerShowTips")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewHandCardTexas")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewPotTexasPoker")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopTypeBase")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewTexasClassic")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewTexasMTT")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DealerEx")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewMTTGameResult")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemMttRewardItem")
    local view_mttresult_fac = ViewMTTGameResultFactory:new(nil, "MTTGameResult", "MTTGameResult", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("MTTGameResult", view_mttresult_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewMTTProcess")
    local view_mttprocess_fac = ViewMTTProcessFactory:new(nil, "MTTProcess", "MTTProcess", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("MTTProcess", view_mttprocess_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("UiCardCommonEx")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("UiCardDealingEx")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("UiChipEx")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("UiChipMgrEx")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewPlayerGiftAndVIP")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopPlayerTexas")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopBase")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopTexas")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHelperBase")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHelperTexas")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopTypeBase")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopTexasClassic")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopTexasMTT")
    local view_desktoptexas_fac = ViewDesktopTexasFactory:new(nil, "Desktop", "Desktop", "Background", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("DesktopTexas", view_desktoptexas_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopPlayerInfoTexas")
    local view_desktopplayerinfotexas_fac = ViewDesktopPlayerInfoTexasFactory:new(nil, "DesktopPlayerInfo", "DesktopPlayerInfo", "SceneActor", false, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("DesktopPlayerInfoTexas", view_desktopplayerinfotexas_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopPlayerOperateTexas")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopFastBet")
    local view_desktopoperatetexas_fac = ViewDesktopPlayerOperateTexasFactory:new(nil, "DesktopPlayerOperate", "DesktopPlayerOperate", "PlayerOperateUi", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("DesktopPlayerOperateTexas", view_desktopoperatetexas_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewLockChatTexas")
    local view_lockchattexas_fac = ViewLockChatTexasFactory:new(nil, "LockChat", "LockChat", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("LockChatTexas", view_lockchattexas_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopHintsTexas")
    local view_desktophintstexas_fac = ViewDesktopHintsTexasFactory:new(nil, "DesktopHints", "DesktopHints", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("DesktopHintsTexas", view_desktophintstexas_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopMenuTexas")
    local view_desktopmenutexas_fac = ViewDesktopMenuTexasFactory:new(nil, "DesktopMenu", "DesktopMenu", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("DesktopMenuTexas", view_desktopmenutexas_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopChatExpression")
    local view_desktopchatexp_fac = ViewDesktopChatExpressionFactory:new(nil, "ChatExPression", "ChatExPression", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("ChatExPression", view_desktopchatexp_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopH")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopHBase")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopHTexas")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHBase")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHTexas")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHUiGold")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHDealer")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHBankPlayer")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHCard")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHCards")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHCardTypeBase")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHCardTypeTexas")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHGoldPool")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHRewardPot")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHSelf")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHStandPlayer")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHChair")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHChair")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("GoldController")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("DesktopHBetPot")
    local view_desktoph_fac = ViewDesktopHFactory:new(nil, "DesktopH", "DesktopH", "Background", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("DesktopH", view_desktoph_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopHBankList")
    local view_desktophbanklist_fac = ViewDesktopHBankListFactory:new(nil, "DesktopHBankPlayerList", "DesktopHBankPlayerList", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("DesktopHBankList", view_desktophbanklist_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopHBetReward")
    local view_desktophbetreward_fac = ViewDesktopHBetRewardFactory:new(nil, "DesktopHBetReward", "DesktopHBetReward", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("DesktopHBetReward", view_desktophbetreward_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopHCardType")
    local view_desktophcardtype_fac = ViewDesktopHCardTypeFactory:new(nil, "DesktopHCardType", "DesktopHCardType", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("DesktopHCardType", view_desktophcardtype_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopHHelp")
    local view_desktophhelp_fac = ViewDesktopHHelpFactory:new(nil, "DesktopHHelp", "DesktopHHelp", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("DesktopHHelp", view_desktophhelp_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopHHistory")
    local view_desktophhistory_fac = ViewDesktopHHistoryFactory:new(nil, "DesktopHHistory", "DesktopHHistory", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("DesktopHHistory", view_desktophhistory_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopHMenu")
    local view_desktophmenu_fac = ViewDesktopHMenuFactory:new(nil, "DesktopHMenu", "DesktopHMenu", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("DesktopHMenu", view_desktophmenu_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopHResult")
    local view_desktophresult_fac = ViewDesktopHResultFactory:new(nil, "DesktopHResult", "DesktopHResult", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("DesktopHResult", view_desktophresult_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopHSetCardType")
    local view_desktophsetcardtype_fac = ViewDesktopHSetCardTypeFactory:new(nil, "DesktopHSetCardType", "DesktopHSetCardType", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("DesktopHSetCardType", view_desktophsetcardtype_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDesktopHRewardPot")
    local view_desktophrewardpot_fac = ViewDesktopHRewardPotFactory:new(nil, "DesktopHRewardPot", "DesktopHRewardPot", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("DesktopHRewardPot", view_desktophrewardpot_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewAgreeOrDisAddFriendRequest")
    local view_agreefriend_fac = ViewAgreeOrDisAddFriendRequestFactory:new(nil, "AgreeOrDisAddFriendRequest", "AgreeOrDisAddFriendRequest", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("AgreeOrDisAddFriendRequest", view_agreefriend_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewBag")
    local view_bag_fac = ViewBagFactory:new(nil, "Bag", "Bag", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("Bag", view_bag_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewBank")
    local view_bank_fac = ViewBankFactory:new(nil, "Bank", "Bank", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("Bank", view_bank_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewChat")
    local view_chat_fac = ViewChatFactory:new(nil, "Chat", "Chat", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("Chat", view_chat_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewChatChooseTarget")
    local view_chatchoose_fac = ViewChatChooseTargetFactory:new(nil, "ChatChooseTarget", "ChatChooseTarget", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("ChatChooseTarget", view_chatchoose_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewChatFriend")
    local view_chatfriend_fac = ViewChatFriendFactory:new(nil, "ChatFriend", "ChatFriend", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("ChatFriend", view_chatfriend_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewChipOperate")
    local view_chipoperate_fac = ViewChipOperateFactory:new(nil, "ChipOperate", "ChipOperate", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("ChipOperate", view_chipoperate_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewChooseLan")
    local view_chooselan_fac = ViewChooseLanFactory:new(nil, "ChooseLan", "ChooseLan", "Background", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("ChooseLan", view_chooselan_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewShare")
    local view_share_fac = ViewShareFactory:new(nil, "Share", "Share", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("Share", view_share_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewCreateDesktop")
    local view_createdesktop_fac = ViewCreateDesktopFactory:new(nil, "CreateDeskTop", "CreateDeskTop", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("CreateDeskTop", view_createdesktop_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewDailyReward")
    local view_dailyreward_fac = ViewDailyRewardFactory:new(nil, "DailyReward", "DailyReward", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("DailyReward", view_dailyreward_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewEdit")
    local view_edit_fac = ViewEditFactory:new(nil, "Edit", "Edit", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("Edit", view_edit_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewFriend")
    local view_friend_fac = ViewFriendFactory:new(nil, "Friend", "Friend", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("Friend", view_friend_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewFriendOnLine")
    local view_friendonline_fac = ViewFriendOnLineFactory:new(nil, "FriendOnLine", "FriendOnLine", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("FriendOnLine", view_friendonline_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewGiftDetail")
    local view_giftdetail_fac = ViewGiftDetailFactory:new(nil, "GiftDetail", "GiftDetail", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("GiftDetail", view_giftdetail_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewGiftShop")
    local view_giftshop_fac = ViewGiftShopFactory:new(nil, "GiftShop", "GiftShop", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("GiftShop", view_giftshop_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewGoldTree")
    local view_goldtree_fac = ViewGoldTreeFactory:new(nil, "GoldTree", "GoldTree", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("GoldTree", view_goldtree_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewInviteFriendPlay")
    local view_invite_fac = ViewInviteFriendPlayFactory:new(nil, "InviteFriendPlay", "InviteFriendPlay", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("InviteFriendPlay", view_invite_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewLobby")
    local view_classicmodel_fac = ViewLobbyFactory:new(nil, "ClassicModel", "ClassicModel", "Background", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("ClassicModel", view_classicmodel_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewMail")
    local view_viewmail_fac = ViewMailFactory:new(nil, "Mail", "Mail", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("Mail", view_viewmail_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewMain")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewOnlineReward")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("UiMainPlayerInfo")
    local view_viewmain_fac = ViewMainFactory:new(nil, "Main", "Main", "Background", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("Main", view_viewmain_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewPlayerInfo")
    local view_playerinfo_fac = ViewPlayerInfoFactory:new(nil, "PlayerInfo", "PlayerInfo", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("PlayerInfo", view_playerinfo_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewPlayerProfile")
    local view_playerprofile_fac = ViewPlayerProfileFactory:new(nil, "PlayerProfile", "PlayerProfile", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("PlayerProfile", view_playerprofile_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewActivityCenter")
    local view_activitycenter_fac = ViewActivityCenterFactory:new(nil, "ActivityCenter", "ActivityCenter", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("ActivityCenter", view_activitycenter_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewQuitOrBack")
    local view_back_fac = ViewQuitOrBackFactory:new(nil, "QuitOrBack", "QuitOrBack", "QuitGame", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("QuitOrBack", view_back_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewRanking")
    local view_ranking_fac = ViewRankingFactory:new(nil, "Ranking", "Ranking", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("Ranking", view_ranking_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewRechargeFirst")
    local view_recharge_fac = ViewRechargeFirstFactory:new(nil, "RechargeFirst", "RechargeFirst", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("RechargeFirst", view_recharge_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewResetPwd")
    local view_resetpwd_fac = ViewResetPwdFactory:new(nil, "ResetPwd", "ResetPwd", "NomalUi", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("ResetPwd", view_resetpwd_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewShop")
    local view_shop_fac = ViewShopFactory:new(nil, "Shop", "Shop", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("Shop", view_shop_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewPurse")
    local view_purse_fac = ViewPurseFactory:new(nil, "Purse", "Purse", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("Purse", view_purse_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewHeadIcon")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewVIPSign")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewHeadIconBig")
    local view_headionbig_fac = ViewHeadIconBigFactory:new(nil, "Common", "CoHeadIconBig", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("HeadIconBig", view_headionbig_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewActivityPopUpBox")
    local view_activity_popupbox_fac = ViewActivityPopUpBoxFactory:new(nil, "ActivityPopUpBox", "ActivityPopUpBox", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("ActivityPopUpBox", view_activity_popupbox_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewMatchLobby")
    local view_matchlobby_fac = ViewMatchLobbyFactory:new(nil, "MatchLobby", "MatchLobby", "Background", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("MatchLobby", view_matchlobby_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewApplySucceed")
    local view_applysucceed_fac = ViewApplySucceedFactory:new(nil, "ApplySucceed", "ApplySucceed", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("ApplySucceed", view_applysucceed_fac)
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewMatchInfo")
    local view_matchinfo_fac = ViewMatchInfoFactory:new(nil, "MatchInfo", "MatchInfo", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("MatchInfo", view_matchinfo_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewClub")
    local view_club_fac = ViewClubFactory:new(nil, "Club", "Club", "Background", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("Club", view_club_fac)
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewCreateMatch")
    local view_creatematch = ViewCreateMatchFactory:new(nil, "CreateMatch", "CreateMatch", "NomalUiMain", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("CreateMatch", view_creatematch)
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewBlindTable")
    local view_blindtable = ViewBlindTableFactory:new(nil, "BlindTable", "BlindTable", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("BlindTable", view_blindtable)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewClubHelp")
    local view_clubhelp = ViewClubHelpFactory:new(nil, "ClubHelp", "ClubHelp", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("ClubHelp", view_clubhelp)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewJoinMatch")
    local view_joinmatch = ViewJoinMatchFactory:new(nil, "JoinMatch", "JoinMatch", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
    self.ViewMgr:regView("JoinMatch", view_joinmatch)
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewGetChipEffect")
	local view_getchipeffect = ViewGetChipEffectFactory:new(nil, "GetChipEffect", "GetChipEffect", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
	self.ViewMgr:regView("GetChipEffect", view_getchipeffect)
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewEnterMatchNotify")
	local view_enterMatchNotify = ViewEnterMatchNotifyFactory:new(nil, "EnterMatchNotify", "EnterMatchNotify", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
	self.ViewMgr:regView("EnterMatchNotify", view_enterMatchNotify)
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewSnowBallReward")
	local view_snowBallRewardFactory = ViewSnowBallRewardFactory:new(nil, "SnowBallReward", "SnowBallReward", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
	self.ViewMgr:regView("SnowBallReward", view_snowBallRewardFactory)
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ViewEditAddress")
	local view_editAddressFactory = ViewEditAddressFactory:new(nil, "EditAddress", "EditAddress", "MessgeBox", true, CS.FairyGUI.FitScreen.FitSize)
	self.ViewMgr:regView("EditAddress", view_editAddressFactory)
    --Item
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemDesktopHBeBankPlayerInfo")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemDesktopHBetOperate")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemDesktopHBetPot")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemDesktopHBetReward")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemDesktopHGameEndPotResult")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemDesktopHGameEndWinPlayer")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemDesktopHHistroy")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemDesktopHSeat")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemDesktopHSetCardType")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemUiDesktopHTongPei")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemUiDesktopHTongSha")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemLotteryTicketBetOperate")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemLotteryTicketBetPot")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemLotteryTicketCard")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemLotteryTicketHistory")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemLotteryTicketRewardPotPlayerInfo")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemAttachment")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemBetChipRange")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemChatEx")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemChatPresetMsg")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemDailyReward")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemDesktopHintsInfo")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemDesktopRaiseOperateGFlower")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemHeadIcon")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemHeadIconWithNickName")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemMagicExpIcon")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemMagicExpSender")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemMail")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemNotice")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemNumOperate")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemPlayerChatLock")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemPlayerReport")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemChatDesktop")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemChatTargetInfo")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemChooseChatTargetInfo")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemDesktopHRewardPotPlayerInfo")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemGift")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemGiftType")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemInviteFriendPlay")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemLan")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemLobbyDesk")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemLobbyDeskPlayInfo")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemMainOperate")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemRank")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemReportPlayerOperate")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemShowFriendSimple")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemUiShopConsume")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemUiShopDiamond")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemUiShopGold")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemUiShopVIPInfo")
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemUiShopVIPInfo")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemVIPBuyInfo")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemActivity")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemActivityTitle")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemUiShopGoods")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemUiPurseGold")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemMatchType")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemMatchInfo")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemBlind")
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemMatchInfoBlind") 
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemMatchInfoReward")
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemSnowBallRewardPlayerNum")
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemSnowBallRewardInfo")
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemMatchInfoRank")
end

function KingTexasListener:_regController()
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ControllerLogin")
    local con_login_fac = ControllerLoginFactory:new(nil)
    self.ControllerMgr:RegController("Login", con_login_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ControllerUCenter")
    local con_ucenter_fac = ControllerUCenterFactory:new(nil)
    self.ControllerMgr:RegController("UCenter", con_ucenter_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ControllerActivity")
    local con_activity_fac = ControllerActivityFactory:new(nil)
    self.ControllerMgr:RegController("Activity", con_activity_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ControllerActor")
    local con_actor_fac = ControllerActorFactory:new(nil)
    self.ControllerMgr:RegController("Actor", con_actor_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ControllerBag")
    local con_bag_fac = ControllerBagFactory:new(nil)
    self.ControllerMgr:RegController("Bag", con_bag_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ControllerDesk")
    local con_desk_fac = ControllerDeskFactory:new(nil)
    self.ControllerMgr:RegController("Desk", con_desk_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ControllerDeskH")
    local con_deskh_fac = ControllerDeskHFactory:new(nil)
    self.ControllerMgr:RegController("DeskH", con_deskh_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ControllerGrow")
    local con_grow_fac = ControllerGrowFactory:new(nil)
    self.ControllerMgr:RegController("Grow", con_grow_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ControllerIM")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("IMChat")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("IMChatRecord")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("IMFriendList")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("IMMailBox")
    local con_im_fac = ControllerIMFactory:new(nil)
    self.ControllerMgr:RegController("IM", con_im_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ControllerLobby")
    local con_lobby_fac = ControllerLobbyFactory:new(nil)
    self.ControllerMgr:RegController("Lobby", con_lobby_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ControllerLotteryTicket")
    local con_lottery_fac = ControllerLotteryTicketFactory:new(nil)
    self.ControllerMgr:RegController("LotteryTicket", con_lottery_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ControllerMarquee")
    local con_marquee_fac = ControllerMarqueeFactory:new(nil)
    self.ControllerMgr:RegController("Marquee", con_marquee_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ControllerPlayer")
    local con_player_fac = ControllerPlayerFactory:new(nil)
    self.ControllerMgr:RegController("Player", con_player_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ControllerRanking")
    local con_ranking_fac = ControllerRankingFactory:new(nil)
    self.ControllerMgr:RegController("Ranking", con_ranking_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ControllerTrade")
    local con_trade_fac = ControllerTradeFactory:new(nil)
    self.ControllerMgr:RegController("Trade", con_trade_fac)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ControllerMTT")
    local con_mtt = ControllerMTTFactory:new(nil)
    self.ControllerMgr:RegController("Mtt", con_mtt)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("Prop")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("Item")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ItemData1")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("Unit")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("UnitBilling")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("UnitConsume")
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("UnitGoodsVoucher")
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("UnitGoldPackage")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("UnitGiftNormal")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("UnitGiftTmp")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("UnitMagicExpression")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("OnLineReward")
end

function KingTexasListener:_addUiPackage()
    local casinos_context = CS.Casinos.CasinosContext.Instance
    local s = self.ViewMgr:getUiPackagePath("LotteryTicket")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("Chat")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("ChatFriend")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("About")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("Mail")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("PayType")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("Common")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("ChooseLan")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("Share")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("Loading")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("LanEn")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("LanZh")
    casinos_context.Listener:AddUiPackage(s)
    if CS.Casinos.CasinosContext.Instance.UnityAndroid then
        s = self.ViewMgr:getUiPackagePath("LanZhAndroid")
        casinos_context.Listener:AddUiPackage(s)
    end
    s = self.ViewMgr:getUiPackagePath("Pool")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("ChatChooseTarget")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("ChatExPression")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("CreateDeskTop")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("AgreeOrDisAddFriendRequest")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("Bank")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("ChipOperate")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("QuitOrBack")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("Login")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("Main")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("Bag")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("MailDetail")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DailyReward")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("Desktop")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopChatParent")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopPlayerInfo")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopPlayerOperate")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DeskTopMenu")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopHints")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("MTTGameResult")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("MTTProcess")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("Friend")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("InviteFriendPlay")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("ResetPwd")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("Ranking")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopH")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopHBetReward")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopHTexas")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopHBankPlayerList")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopHCardType")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopHHistory")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopHRewardPot")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopHMenu")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopHHelp")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopHResult")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopHSetCardType")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopHTongSha")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopHTongPei")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("Edit")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("FriendOnLine")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("GiftDetail")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("GiftShop")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("LockChat")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("PlayerProfile")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("PlayerInfo")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("Notice")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("ShootingText")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("Shop")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("Purse")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("TakePhoto")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("ClassicModel")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("RechargeFirst")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("ActivityPopUpBox")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("ActivityCenter")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("MatchLobby")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("ApplySucceed")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("Club")
    casinos_context.Listener:AddUiPackage(s)
	s = self.ViewMgr:getUiPackagePath("CreateMatch")
    casinos_context.Listener:AddUiPackage(s)
	s = self.ViewMgr:getUiPackagePath("BlindTable")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("ClubHelp")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("JoinMatch")
    casinos_context.Listener:AddUiPackage(s)
	s = self.ViewMgr:getUiPackagePath("GetChipEffect")
	casinos_context.Listener:AddUiPackage(s)
	s = self.ViewMgr:getUiPackagePath("MatchInfo")
	casinos_context.Listener:AddUiPackage(s)
	s = self.ViewMgr:getUiPackagePath("EnterMatchNotify")
	casinos_context.Listener:AddUiPackage(s)
	s = self.ViewMgr:getUiPackagePath("SnowBallReward")
	casinos_context.Listener:AddUiPackage(s)
	s = self.ViewMgr:getUiPackagePath("EditAddress")
	casinos_context.Listener:AddUiPackage(s)

	--[[s = self.ViewMgr:getUiPackagePath("DesktopGFlower")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopMenuGFlower")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopPlayerInfoGFlower")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("DesktopPlayerOperateGFlower")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("LobbyGFlower")]]

    --[[s = self.ViewMgr:getUiPackagePath("ForestParty")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("ForestPartyMenu")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("ForestPartyRule")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("ForestPartyInfo")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("ForestPartyBet")
    casinos_context.Listener:AddUiPackage(s)
    s = self.ViewMgr:getUiPackagePath("ForestPartyResult")
    casinos_context.Listener:AddUiPackage(s)]]--
end

function KingTexasListener:RegTbData()
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataHintsInfoTexas")
    self.TbDataMgr:RegTbDataFac("HintsInfoTexas", TbDataFactoryHintsInfoTexas:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataActorLevel")
    self.TbDataMgr:RegTbDataFac("ActorLevel", TbDataFactoryActorLevel:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataCommon")
    self.TbDataMgr:RegTbDataFac("Common", TbDataFactoryCommon:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDailyReward")
    self.TbDataMgr:RegTbDataFac("DailyReward", TbDataFactoryDailyReward:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataExpression")
    self.TbDataMgr:RegTbDataFac("Expression", TbDataFactoryExpression:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataItem")
    self.TbDataMgr:RegTbDataFac("Item", TbDataFactoryItem:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataItemType")
    self.TbDataMgr:RegTbDataFac("ItemType", TbDataFactoryItemType:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataLanEn")
    self.TbDataMgr:RegTbDataFac("LanEn", TbDataFactoryLanEn:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataLans")
    self.TbDataMgr:RegTbDataFac("Lans", TbDataFactoryLans:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataLanZh")
    self.TbDataMgr:RegTbDataFac("LanZh", TbDataFactoryLanZh:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataLotteryTicket")
    self.TbDataMgr:RegTbDataFac("LotteryTicket", TbDataFactoryLotteryTicket:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataLotteryTicketBetOperate")
    self.TbDataMgr:RegTbDataFac("LotteryTicketBetOperate", TbDataFactoryLotteryTicketBetOperate:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataLotteryTicketGoldPercent")
    self.TbDataMgr:RegTbDataFac("LotteryTicketGoldPercent", TbDataFactoryLotteryTicketGoldPercent:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataOnlineReward")
    self.TbDataMgr:RegTbDataFac("OnlineReward", TbDataFactoryOnlineReward:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataPresetMsg")
    self.TbDataMgr:RegTbDataFac("PresetMsg", TbDataFactoryPresetMsg:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataUnitBilling")
    self.TbDataMgr:RegTbDataFac("UnitBilling", TbDataFactoryUnitBilling:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataUnitConsume")
    self.TbDataMgr:RegTbDataFac("UnitConsume", TbDataFactoryUnitConsume:new(nil))
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataUnitGoodsVoucher")
    self.TbDataMgr:RegTbDataFac("UnitGoodsVoucher", TbDataFactoryUnitGoodsVoucher:new(nil))
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataUnitGoldPackage")
    self.TbDataMgr:RegTbDataFac("UnitGoldPackage", TbDataFactoryUnitGoldPackage:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataUnitGiftNormal")
    self.TbDataMgr:RegTbDataFac("UnitGiftNormal", TbDataFactoryUnitGiftNormal:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataUnitGiftTmp")
    self.TbDataMgr:RegTbDataFac("UnitGiftTmp", TbDataFactoryUnitGiftTmp:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataUnitMagicExpression")
    self.TbDataMgr:RegTbDataFac("UnitMagicExpression", TbDataFactoryUnitMagicExpression:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataVIPLevel")
    self.TbDataMgr:RegTbDataFac("VIPLevel", TbDataFactoryVIPLevel:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataConfigTexasDesktop")
    self.TbDataMgr:RegTbDataFac("ConfigTexasDesktop", TbDataFactoryConfigTexasDesktop:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopInfoTexas")
    self.TbDataMgr:RegTbDataFac("DesktopInfoTexas", TbDataFactoryDesktopInfoTexas:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataCfigTexasDesktopH")
    self.TbDataMgr:RegTbDataFac("CfigTexasDesktopH", TbDataFactoryCfigTexasDesktopH:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataCfigTexasDesktopHGoldPercent")
    self.TbDataMgr:RegTbDataFac("CfigTexasDesktopHGoldPercent", TbDataFactoryCfigTexasDesktopHGoldPercent:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataCfigTexasDesktopHSysBank")
    self.TbDataMgr:RegTbDataFac("CfigTexasDesktopHSysBank", TbDataFactoryCfigTexasDesktopHSysBank:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopHBetOperateTexas")
    self.TbDataMgr:RegTbDataFac("DesktopHBetOperateTexas", TbDataFactoryDesktopHBetOperateTexas:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopHBetPotTexas")
    self.TbDataMgr:RegTbDataFac("DesktopHBetPotTexas", TbDataFactoryDesktopHBetPotTexas:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopHInfoTexas")
    self.TbDataMgr:RegTbDataFac("DesktopHInfoTexas", TbDataFactoryDesktopHInfoTexas:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopHBetReward")
    self.TbDataMgr:RegTbDataFac("DesktopHBetReward", TbDataFactoryDesktopHBetReward:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataTexasRaiseBlinds")
    self.TbDataMgr:RegTbDataFac("TexasRaiseBlinds", TbDataFactoryTexasRaiseBlinds:new(nil))
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopFastBet")
    self.TbDataMgr:RegTbDataFac("DesktopFastBet", TbDataFactoryDesktopFastBet:new(nil))
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataTexasSnowBallRewardPlayerNum")
    self.TbDataMgr:RegTbDataFac("TexasSnowBallRewardPlayerNum", TbDataFactoryTexasSnowBallRewardPlayerNum:new(nil))
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataTexasSnowBallRewardInfo")
    self.TbDataMgr:RegTbDataFac("TexasSnowBallRewardInfo", TbDataFactoryTexasSnowBallRewardInfo:new(nil))
	




    --[[CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataConfigGFlowerDesktop")
self.TbDataMgr:RegTbDataFac("ConfigGFlowerDesktop",TbDataFactoryConfigGFlowerDesktop:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopGFlowerBetOperate")
self.TbDataMgr:RegTbDataFac("DesktopGFlowerBetOperate",TbDataFactoryDesktopGFlowerBetOperate:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopGFlowerCreateInfo")
self.TbDataMgr:RegTbDataFac("DesktopGFlowerCreateInfo",TbDataFactoryDesktopGFlowerCreateInfo:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopInfoGFlower")
self.TbDataMgr:RegTbDataFac("DesktopInfoGFlower",TbDataFactoryDesktopInfoGFlower:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataCfigGFlowerDesktopH")
self.TbDataMgr:RegTbDataFac("CfigGFlowerDesktopH",TbDataFactoryCfigGFlowerDesktopH:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataCfigGFlowerDesktopHGoldPercent")
self.TbDataMgr:RegTbDataFac("CfigGFlowerDesktopHGoldPercent",TbDataFactoryCfigGFlowerDesktopHGoldPercent:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataCfigGFlowerDesktopHSysBank")
self.TbDataMgr:RegTbDataFac("CfigGFlowerDesktopHSysBank",TbDataFactoryCfigGFlowerDesktopHSysBank:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopHBetOperateGFlower")
self.TbDataMgr:RegTbDataFac("DesktopHBetOperateGFlower",TbDataFactoryDesktopHBetOperateGFlower:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopHBetPotGFlower")
self.TbDataMgr:RegTbDataFac("DesktopHBetPotGFlower",TbDataFactoryDesktopHBetPotGFlower:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopHInfoGFlower")
self.TbDataMgr:RegTbDataFac("DesktopHInfoGFlower",TbDataFactoryDesktopHInfoGFlower:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataCfigZhongFBDesktopH")
self.TbDataMgr:RegTbDataFac("CfigZhongFBDesktopH",TbDataFactoryCfigZhongFBDesktopH:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataCfigZhongFBDesktopHGoldPercent")
self.TbDataMgr:RegTbDataFac("CfigZhongFBDesktopHGoldPercent",TbDataFactoryCfigZhongFBDesktopHGoldPercent:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataCfigZhongFBDesktopHSysBank")
self.TbDataMgr:RegTbDataFac("CfigZhongFBDesktopHSysBank",TbDataFactoryCfigZhongFBDesktopHSysBank:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopHBetOperateZhongFB")
self.TbDataMgr:RegTbDataFac("DesktopHBetOperateZhongFB",TbDataFactoryDesktopHBetOperateZhongFB:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopHBetPotZhongFB")
self.TbDataMgr:RegTbDataFac("DesktopHBetPotZhongFB",TbDataFactoryDesktopHBetPotZhongFB:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopHInfoZhongFB")
self.TbDataMgr:RegTbDataFac("DesktopHInfoZhongFB",TbDataFactoryDesktopHInfoZhongFB:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataCfigNiuNiuDesktopH")
self.TbDataMgr:RegTbDataFac("CfigNiuNiuDesktopH",TbDataFactoryCfigNiuNiuDesktopH:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataCfigNiuNiuDesktopHGoldPercent")
self.TbDataMgr:RegTbDataFac("CfigNiuNiuDesktopHGoldPercent",TbDataFactoryCfigNiuNiuDesktopHGoldPercent:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataCfigNiuNiuDesktopHSysBank")
self.TbDataMgr:RegTbDataFac("CfigNiuNiuDesktopHSysBank",TbDataFactoryCfigNiuNiuDesktopHSysBank:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopHBetOperateNiuNiu")
self.TbDataMgr:RegTbDataFac("DesktopHBetOperateNiuNiu",TbDataFactoryDesktopHBetOperateNiuNiu:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopHBetPotNiuNiu")
self.TbDataMgr:RegTbDataFac("DesktopHBetPotNiuNiu",TbDataFactoryDesktopHBetPotNiuNiu:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataDesktopHInfoNiuNiu")
self.TbDataMgr:RegTbDataFac("DesktopHInfoNiuNiu",TbDataFactoryDesktopHInfoNiuNiu:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataForestPartyAnimalList")
self.TbDataMgr:RegTbDataFac("ForestPartyAnimalList",TbDataFactoryForestPartyAnimalList:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataForestPartyBetOperate")
self.TbDataMgr:RegTbDataFac("ForestPartyBetOperate",TbDataFactoryForestPartyBetOperate:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataForestPartyBetPotMultiple")
self.TbDataMgr:RegTbDataFac("ForestPartyBetPotMultiple",TbDataFactoryForestPartyBetPotMultiple:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataForestPartyDesktop")
self.TbDataMgr:RegTbDataFac("ForestPartyDesktop",TbDataFactoryForestPartyDesktop:new(nil))
CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataForestPartyLottery")
self.TbDataMgr:RegTbDataFac("ForestPartyLottery",TbDataFactoryForestPartyLottery:new(nil))]]--
end

function KingTexasListener:LoadDataDone()
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("TbDataHelper")
    TbDataHelper:new(nil, self.TbDataMgr)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ModelCommon")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ModelAccount")
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ModelActor")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ModelWallet")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ModelUCenter")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ModelTrade")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ModelDesktop")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ModelDesktopTexas")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ModelDesktopTexasMatch")
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ModelActivity")
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ModelGrow") 
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ModelPlayer")
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ModelRank")
	CS.Casinos.CasinosContext.Instance.CasinosLua:doString("ModelMarquee")

    self.LanMgr = LanMgr:new(nil)
    self.ViewMgr.LanMgr = self.LanMgr
    self.ControllerMgr.LanMgr = self.LanMgr
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("CasinoHelper")
    CasinoHelper:new(nil, self.ViewMgr.RPC.MessagePack, self.LanMgr)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("Native")
    Native:new(nil,self.ViewMgr,self)
    CS.Casinos.CasinosContext.Instance.CasinosLua:doString("PicCapture")
    self.PicCapture = PicCapture:new(nil,self.ViewMgr,self)
    self.LoadTbDataDone = true
    --local mgr = ControllerMgr:new(nil)
    --self.TbDataMgr:ParseTableAllData("HintsInfoTexas")
    --[[data_mgr.ParseTableAllData<TbDataLanEn>(_eTableName.LanEn.ToString());
    data_mgr.ParseTableAllData<TbDataLanZh>(_eTableName.LanZh.ToString());
    data_mgr.ParseTableAllData<TbDataLans>(_eTableName.Lans.ToString());
    data_mgr.ParseTableAllData<TbDataLotteryTicketBetOperate>(_eTableName.LotteryTicketBetOperate.ToString());
    data_mgr.ParseTableAllData<TbDataLotteryTicketGoldPercent>(_eTableName.LotteryTicketGoldPercent.ToString());
    data_mgr.ParseTableAllData<TbDataActorLevel>(_eTableName.ActorLevel.ToString());
    data_mgr.ParseTableAllData<TbDataDesktopHBetReward>(_eTableName.DesktopHBetReward.ToString());
    data_mgr.ParseTableAllData<TbDataDesktopInfoTexas>(_eTableName.DesktopInfoTexas.ToString());
    data_mgr.ParseTableAllData<TbDataDesktopHInfoTexas>(_eTableName.DesktopHInfoTexas.ToString());
    data_mgr.ParseTableAllData<TbDataDesktopHBetPotTexas>(_eTableName.DesktopHBetPotTexas.ToString());
    data_mgr.ParseTableAllData<TbDataDesktopHBetOperateTexas>(_eTableName.DesktopHBetOperateTexas.ToString());
    data_mgr.ParseTableAllData<TbDataCfigTexasDesktopHGoldPercent>(_eTableName.CfigTexasDesktopHGoldPercent.ToString());
    data_mgr.ParseTableAllData<TbDataCfigTexasDesktopH>(_eTableName.CfigTexasDesktopH.ToString());
    data_mgr.ParseTableAllData<TbDataCfigTexasDesktopHSysBank>(_eTableName.CfigTexasDesktopHSysBank.ToString());
    data_mgr.ParseTableAllData<TbDataExpression>(_eTableName.Expression.ToString());
    data_mgr.ParseTableAllData<TbDataCommon>(_eTableName.Common.ToString());
    data_mgr.ParseTableAllData<TbDataDailyReward>(_eTableName.DailyReward.ToString());
    data_mgr.ParseTableAllData<TbDataItem>(_eTableName.Item.ToString());
    data_mgr.ParseTableAllData<TbDataItemType>(_eTableName.ItemType.ToString());
    data_mgr.ParseTableAllData<TbDataPresetMsg>(_eTableName.PresetMsg.ToString());
    data_mgr.ParseTableAllData<TbDataMustBetDesktopInfoTexas>(_eTableName.MustBetDesktopInfoTexas.ToString());
    data_mgr.ParseTableAllData<TbDataUnitBilling>(_eTableName.UnitBilling.ToString());
    data_mgr.ParseTableAllData<TbDataUnitGiftNormal>(_eTableName.UnitGiftNormal.ToString());
    data_mgr.ParseTableAllData<TbDataUnitGiftTmp>(_eTableName.UnitGiftTmp.ToString());
    data_mgr.ParseTableAllData<TbDataVIPLevel>(_eTableName.VIPLevel.ToString());
    data_mgr.ParseTableAllData<TbDataUnitMagicExpression>(_eTableName.UnitMagicExpression.ToString());
    data_mgr.ParseTableAllData<TbDataForestPartyDesktop>(_eTableName.ForestPartyDesktop.ToString());
    data_mgr.ParseTableAllData<TbDataForestPartyBetOperate>(_eTableName.ForestPartyBetOperate.ToString());
    data_mgr.ParseTableAllData<TbDataForestPartyBetPotMultiple>(_eTableName.ForestPartyBetPotMultiple.ToString());
    data_mgr.ParseTableAllData<TbDataDesktopGFlowerBetOperate>(_eTableName.DesktopGFlowerBetOperate.ToString());
    data_mgr.ParseTableAllData<TbDataDesktopInfoGFlower>(_eTableName.DesktopInfoGFlower.ToString());--]]
end